@startuml

' Définir un FontSize global pour tous les éléments
skinparam defaultFontSize 35

' Paramètres de style pour les composants du front-end
skinparam component {
  BackgroundColor<<FrontEnd>> LightGreen
  BorderColor<<FrontEnd>> DarkGreen
  FontColor<<FrontEnd>> Black
}

' Paramètres de style pour les composants du back-end
skinparam component {
  BackgroundColor<<BackEnd>> LightCoral
  BorderColor<<BackEnd>> DarkRed
  FontColor<<BackEnd>> Black
}

' Paramètres de style pour les bases de données
skinparam database {
  BackgroundColor LightSkyBlue
  BorderColor RoyalBlue
  FontColor Black
}

' Paramètres de style pour les services externes
skinparam component {
  BackgroundColor<<ExternalService>> LightGoldenRodYellow
  BorderColor<<ExternalService>> GoldenRod
  FontColor<<ExternalService>> Black
}

package "Front-End" {
  component VueApp <<FrontEnd>> {
    [Interface Utilisateur]
    [Routeur]
    [Gestion d'État]
  }
}

package "Back-End" {
  component LaravelAPI <<BackEnd>> {
    [Contrôleur d'Authentification]
    [Contrôleur de Produits]
    [Contrôleur de Commandes]
    [Middleware]
    [Couche de Service]
  }
}

database MySQL {
  [Table des Utilisateurs]
  [Table des Produits]
  [Table des Commandes]
  [Table des Adresses]
}

package "Services Externes" {
  component "Passerelle de Paiement" <<ExternalService>> {
    [API Stripe]
  }
  component "Service d'Email" <<ExternalService>> {
    [Serveur SMTP]
  }
}

' Connexions et interactions
VueApp -[#green]-> LaravelAPI : "Requêtes HTTP RESTful"
LaravelAPI -[#blue]-> MySQL : "Requêtes SQL Read/Write"
LaravelAPI -[#orange]-> "Passerelle de Paiement" : "Traitement des Paiements"
LaravelAPI -[#brown]-> "Service d'Email" : "Envoi de Notifications par Email"

@enduml
