@startuml

title Diagramme de Packages pour une Application de E-commerce
skinparam titleFontSize 20
skinparam titleFontColor #3A3A3A
skinparam titleBorderColor #3A3A3A

' Définition des couleurs de fond et des bordures
skinparam package {
    BackgroundColor #E5F6FF
    BorderColor #3A3A3A
    FontSize 14
    FontColor #3A3A3A
}

' Définition des composants internes
package "Application de E-commerce" {

    package "Interface Utilisateur" {
        class ApplicationWeb {
            + Accueil
            + DetailProduit
        }

    }

    package "Services Backend" {
        class ServiceProduit {
            + listerProduits()
            + obtenirDetailsProduit()
        }
        class ServiceCommande {
            + creerCommande()
            + annulerCommande()
        }
        class ServiceUtilisateur {
            + enregistrerUtilisateur()
            + connecterUtilisateur()
        }
    }

    package "Bases de Données" {
        class BaseProduits {
            + stockerDonneesProduit()
        }
        class BaseCommandes {
            + traiterDonneesCommande()
        }
        class BaseUtilisateurs {
            + gererDonneesUtilisateur()
        }
    }
}

' Définition des systèmes externes
package "Systèmes Externes" {
    class PasserellePaiement {
        + traiterPaiement()
    }
    class SystemeFournisseur {
        + synchroniserInventaire()
    }
    class ServiceEmail {
        + envoyerEmail()
    }
}

' Connexions
ApplicationWeb --> ServiceProduit : "Accéder aux produits"
ApplicationWeb --> ServiceCommande : "Passer commande"
ServiceCommande --> PasserellePaiement : "Traitement du paiement"
ServiceProduit --> SystemeFournisseur : "Mise à jour de l'inventaire"
ServiceCommande --> ServiceEmail : "Envoi d'e-mails"

@enduml
