@startuml
left to right direction
skinparam packageStyle rectangle

@startuml
left to right direction
skinparam packageStyle rectangle

actor Administrateur
component "Système de Paiement" as PaymentSystem
component "Système d'Email" as EmailSystem
component "Service de Support" as SupportService

rectangle "Système de Commerce Électronique" {
  (Authentification Administrateur) as AuthA
  (Gérer Produits) as GPdts
  (Gérer Catégories) as GC
  (Gérer Utilisateurs) as GU
  (Analyser Ventes) as AV
  (Modifier Paramètres Système) as MPS
  (Superviser Commandes) as SC
  (Gérer Feedbacks Clients) as GFC

  (Intégrer Système de Paiement) as ISP
  (Envoyer Rapports de Ventes) as ERV
  (Support Technique) as ST
}

Administrateur --> AuthA
Administrateur --> GPdts
Administrateur --> GC
Administrateur --> GU
Administrateur --> AV
Administrateur --> MPS
Administrateur --> SC
Administrateur --> GFC

ISP --> PaymentSystem
ERV --> EmailSystem
ST --> SupportService

' Extensions et Inclusions
MPS <|-- ISP : <<include>>
AV <|-- ERV : <<include>>
SC <|-- ST : <<extend>>

@enduml



'' Acteurs
'actor "Utilisateur Enregistré" as Utilisateur_Enregistre
'
'' Système principal
'rectangle "Système de Commerce Électronique" {
'    (Authentification) as Auth
'    (Gérer Panier) as GP
'    (Consulter Historique Commande) as CHC
'    (Modifier Compte) as MC
'    (Configurer Préférences) as CP
'    (Gérer Notifications) as GN
'    (Suivre Commandes) as SC
'    (Recevoir Notifications) as RN
'}
'
'' Système externe
'component "Système de Notification" as NotificationSystem
'
'' Connexions
'Utilisateur_Enregistre --> Auth : "Accède à"
'Utilisateur_Enregistre --> GP : "Gère le"
'Utilisateur_Enregistre --> CHC : "Consulte"
'Utilisateur_Enregistre --> MC : "Modifie"
'Utilisateur_Enregistre --> CP : "Configure"
'Utilisateur_Enregistre --> GN : "Gère"
'Utilisateur_Enregistre --> SC : "Suit"
'GN --> RN : "Envoie"
'RN --> NotificationSystem : "Notifie"


' Acteur
'actor Client
'
'' Systèmes externes
'component "Système d'Email" as EmailSystem
'component "Service de Livraison" as DeliveryService
'
'' Système principal
'rectangle "Système de Commerce Électronique" {
'  (Naviguer Produits) as NP
'  (Ajouter au Panier) as AP
'  (Passer Commande) as PC
'  (Payer Commande) as PayC
'  (Recevoir Confirmation de Commande) as RCC
'  (Suivre Livraison) as SL
'}
'
'' Connexions
'Client --> NP : "Navigue"
'Client --> AP : "Ajoute"
'Client --> PC : "Passe"
'Client --> PayC : "Paye"
'PC --> RCC : "Déclenche"
'RCC --> EmailSystem : "Envoie email"
'PC --> SL : "Initie"
'SL --> DeliveryService : "Suit"




@enduml
