@startuml
left to right direction
skinparam packageStyle rectangle

'actor Administrateur
'actor "Système de Paiement" as PaymentSystem
'actor "Système d'Email" as EmailSystem
'actor "Service de Support" as SupportService
'
'rectangle "Système de Commerce Électronique" {
'    (Authentification Administrateur) as AuthA
'    (Gérer Produits) as GPdts
'    (Gérer Catégories) as GC
'    (Gérer Utilisateurs) as GU
'    (Analyser Ventes) as AV
'    (Modifier Paramètres Système) as MPS
'    (Superviser Commandes) as SC
'    (Intégrer Système de Paiement) as ISP
'    (Envoyer Rapports de Ventes) as ERV
'    (Gérer Feedbacks Clients) as GFC
'    (Support Technique) as ST
'}
'
'Administrateur --> AuthA
'Administrateur --> GPdts
'Administrateur --> GC
'Administrateur --> GU
'Administrateur --> AV
'Administrateur --> MPS
'Administrateur --> SC
'ISP --> PaymentSystem
'ERV --> EmailSystem
'Administrateur --> GFC
'ST --> SupportService



'' Acteurs
'actor "Utilisateur Enregistré" as Utilisateur_Enregistre
'
'' Système principal
'rectangle "Système de Commerce Électronique" {
'    (Authentification) as Auth
'    (Gérer Panier) as GP
'    (Consulter Historique Commande) as CHC
'    (Modifier Compte) as MC
'    (Configurer Préférences) as CP
'    (Gérer Notifications) as GN
'    (Suivre Commandes) as SC
'    (Recevoir Notifications) as RN
'}
'
'' Système externe
'component "Système de Notification" as NotificationSystem
'
'' Connexions
'Utilisateur_Enregistre --> Auth : "Accède à"
'Utilisateur_Enregistre --> GP : "Gère le"
'Utilisateur_Enregistre --> CHC : "Consulte"
'Utilisateur_Enregistre --> MC : "Modifie"
'Utilisateur_Enregistre --> CP : "Configure"
'Utilisateur_Enregistre --> GN : "Gère"
'Utilisateur_Enregistre --> SC : "Suit"
'GN --> RN : "Envoie"
'RN --> NotificationSystem : "Notifie"


' Acteur
actor Client

' Systèmes externes
component "Système d'Email" as EmailSystem
component "Service de Livraison" as DeliveryService

' Système principal
rectangle "Système de Commerce Électronique" {
    (Créer un Compte) as CCA
    (Authentification) as Auth
    (Gérer Informations Client) as GIC
    (Naviguer Produits) as NP
    (Ajouter au Panier) as AP
    (Passer Commande) as PC
    (Payer Commande) as PayC
    (Consulter Commandes) as CC
    (Gérer Adresses) as GA
    (Évaluer Produits) as EP
    (Recevoir Confirmation de Commande) as RCC
    (Suivre Livraison) as SL
}

' Connexions
Client --> CCA : "Crée"
Client --> Auth : "S'authentifie"
Client --> GIC : "Gère"
Client --> NP : "Navigue"
Client --> AP : "Ajoute"
Client --> PC : "Passe"
Client --> PayC : "Paye"
Client --> CC : "Consulte"
Client --> GA : "Gère"
Client --> EP : "Évalue"
PC --> RCC : "Déclenche"
RCC --> EmailSystem : "Envoie email"
PC --> SL : "Initie"
SL --> DeliveryService : "Suit"

@enduml
